In [1]:
import numpy as np
import time
time_start = time.time()
X = np.genfromtxt('00_Data/train_X_dog_cat.csv', delimiter=',')
y = np.genfromtxt('00_Data/train_y_dog_cat.csv', delimiter=',')
print(X.shape)

n = X.shape[0]
d = X.shape[1]
print(y.shape)
time_end = time.time()
print("Done loading training data, using time:(min)", (time_end-time_start)/60)

(1953, 3072)
(1953,)
Done loading training data, using time:(min) 0.07759588162104289


In [2]:
X_test = np.genfromtxt('00_Data/test_X_dog_cat.csv', delimiter=',')
y_test = np.genfromtxt('00_Data/test_y_dog_cat.csv', delimiter=',')
m = X_test.shape[0]
print(m)

2000


In [93]:
from sklearn import preprocessing
scaler = preprocessing.StandardScaler().fit(X)
X_scaled = scaler.transform(X)
X_test = scaler.transform(X_test)


In [77]:
def linear_kernel(x1,x2):
    # x1 = (n,d) X2 = (m,d)
    return(np.dot(x1,x2.T))

def inhomogeneous_poly_kernel(x1,x2):
    n = x1.shape[0]
    m = x2.shape[0]
    return(np.power(np.ones(shape=(n,m)) + np.dot(x1,x2.T), 5))

def gaussian_kernel(x1,x2):
    from sklearn.gaussian_process.kernels import RBF
    return(RBF()(x1,x2))

In [83]:
X = X_scaled
print(X[0])
print(X[1])
print(linear_kernel(X[0],X[1]))


[ 0.0004468  -0.00031918 -0.00079461 ... -0.00159203 -0.0014244
 -0.00129383]
[-0.00035454  0.00140669  0.00186243 ... -0.00283852 -0.00277895
 -0.00263179]
0.003661717580371986


In [49]:
def probability(alpha, Ki):
    s = np.dot(alpha, Ki)
    return(1/(1+np.exp(-s)))

def train(X,y):
    time_start = time.time()
    alpha = np.random.uniform(size=(n))
    #alpha = np.zeros(n)
    for t in range(max_iter):
        samples = np.random.permutation(n)[:batch_size]
        g = regu_para*alpha
        #g = np.zeros(n)
        for i in samples:
            pi = probability(alpha, K[i])
            g[i] = g[i] + (pi - (y[i]+1)/2.0)
        alpha = alpha - eta*g
        #print(alpha)
        print(evaluation(prediction(K,alpha), y))
    time_end = time.time()
    print("Done training, using time:(min)", 
          (time_end-time_start)/60)
    return(alpha)

In [42]:

def prediction(K_test,alpha):
    #K_test = kernel(X, X_test)
    return(probability(alpha,K_test))


In [69]:
def evaluation(ans, y_test):
    right = 0
    for i in range(ans.shape[0]):
        if (ans[i] - 0.5)*y_test[i] >= 0:
            right += 1
    return(right/float(m))

In [84]:
kernel = gaussian_kernel
K = kernel(X_scaled,X_scaled)


In [91]:
max_iter = 500
batch_size = 100
regu_para = 2.0
eta = 1

In [94]:
alpha = train(X_scaled,y)
print(alpha)

[-10.25006137 -18.38676883  -3.19350886 ... -15.78577082 -12.79537868
 -15.31392718]
0.508
[194.75116603 349.34860782  60.67666838 ... 299.92964559 243.11219486
 290.96461649]
0.4685
[-3700.27215464 -6647.62354851 -1152.85669917 ... -5698.66326627
 -4619.13170234 -5528.32771339]
0.508
[ 70305.1709381  126304.84742162  21904.27728414 ... 108274.60205908
  87773.50234454 105038.22655434]
0.4685
[-1335798.24782398 -2399792.10101086  -416191.26839869 ...
 -2057217.43912247 -1667696.54454621 -1995726.30453242]
0.508
[25380166.70865561 45596049.91920636  7907634.09957504 ...
 39087131.34332699 31686244.34637807 37918799.78611594]
0.4685
[-4.82223167e+08 -8.66324948e+08 -1.50245048e+08 ... -7.42655496e+08
 -6.02038643e+08 -7.20457196e+08]
0.508
[9.16224018e+09 1.64601740e+10 2.85465591e+09 ... 1.41104544e+10
 1.14387342e+10 1.36886867e+10]
0.4685
[-1.74082563e+11 -3.12743306e+11 -5.42384623e+10 ... -2.68098634e+11
 -2.17335950e+11 -2.60085048e+11]
0.508
[3.30756871e+12 5.94212282e+12 1.030530

/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:3: RuntimeWarning: overflow encountered in exp
  This is separate from the ipykernel package so we can avoid doing imports until


0.508
[1.29463013e+61 2.32583264e+61 4.03364623e+60 ... 1.99381582e+61
 1.61630013e+61 1.93421979e+61]
0.4685
[-2.45979725e+62 -4.41908201e+62 -7.66392783e+61 ... -3.78825006e+62
 -3.07097024e+62 -3.67501760e+62]
0.508
[4.67361477e+63 8.39625582e+63 1.45614629e+63 ... 7.19767512e+63
 5.83484346e+63 6.98253344e+63]
0.4685
[-8.87986807e+64 -1.59528861e+65 -2.76667795e+64 ... -1.36755827e+65
 -1.10862026e+65 -1.32668135e+65]
0.508
[1.68717493e+66 3.03104835e+66 5.25668810e+65 ... 2.59836072e+66
 2.10637849e+66 2.52069457e+66]
0.4685
[-3.20563237e+67 -5.75899187e+67 -9.98770739e+66 ... -4.93688536e+67
 -4.00211913e+67 -4.78931969e+67]
0.508
[6.09070151e+68 1.09420845e+69 1.89766440e+68 ... 9.38008219e+68
 7.60402634e+68 9.09970741e+68]
0.4685
[-1.15723329e+70 -2.07899606e+70 -3.60556237e+69 ... -1.78221562e+70
 -1.44476500e+70 -1.72894441e+70]
0.508
[2.19874324e+71 3.95009252e+71 6.85056850e+70 ... 3.38620967e+71
 2.74505351e+71 3.28499437e+71]
0.4685
[-4.17761216e+72 -7.50517579e+72 -1.30

0.508
[7.45575111e+183 1.33944274e+184 2.32296944e+183 ... 1.14823486e+184
 9.30824270e+183 1.11391362e+184]
0.4685
[-1.41659271e+185 -2.54494120e+185 -4.41364194e+184 ... -2.18164624e+185
 -1.76856611e+185 -2.11643588e+185]
0.508
[2.69152615e+186 4.83538828e+186 8.38591969e+185 ... 4.14512786e+186
 3.36027561e+186 4.02122817e+186]
0.4685
[-5.11389969e+187 -9.18723774e+187 -1.59332474e+187 ... -7.87574294e+187
 -6.38452367e+187 -7.64033352e+187]
0.508
[9.71640941e+188 1.74557517e+189 3.02731701e+188 ... 1.49639116e+189
 1.21305950e+189 1.45166337e+189]
0.4685
[-1.84611779e+190 -3.31659282e+190 -5.75190231e+189 ... -2.84314320e+190
 -2.30481304e+190 -2.75816040e+190]
0.508
[3.50762380e+191 6.30152637e+191 1.09286144e+191 ... 5.40197208e+191
 4.37914478e+191 5.24050476e+191]
0.4685
[-6.66448521e+192 -1.19729001e+193 -2.07643674e+192 ... -1.02637470e+193
 -8.32037509e+192 -9.95695904e+192]
0.508
[1.26625219e+194 2.27485102e+194 3.94522980e+193 ... 1.95011192e+194
 1.58087127e+194 1.891822

 1.13944085e+299 1.36356423e+299]
0.4685
[-1.73407984e+300 -3.11531409e+300 -5.40282852e+299 ... -2.67059737e+300
 -2.16493761e+300 -2.59077204e+300]
0.508
[3.29475169e+301 5.91909676e+301 1.02653742e+301 ... 5.07413500e+301
 4.11338146e+301 4.92246687e+301]
0.4685
[-6.26002821e+302 -1.12462838e+303 -1.95042110e+302 ... -9.64085649e+302
 -7.81542477e+302 -9.35268705e+302]
0.508
[1.18940536e+304 2.13679393e+304 3.70580008e+303 ... 1.83176273e+304
 1.48493071e+304 1.77701054e+304]
0.4685
[-2.25987018e+305 -4.05990847e+305 -7.04102016e+304 ... -3.48034919e+305
 -2.82136834e+305 -3.37632002e+305]
0.508
[4.29375335e+306 7.71382609e+306 1.33779383e+306 ... 6.61266347e+306
 5.36059985e+306 6.41500805e+306]
0.4685
[-8.15813137e+307 -1.46562696e+308 -2.54180828e+307 ... -1.25640606e+308
 -1.01851397e+308 -1.21885153e+308]
0.508
[inf inf inf ... inf inf inf]
0.0
[nan nan nan ... nan nan nan]
0.0
[nan nan nan ... nan nan nan]
0.0
[nan nan nan ... nan nan nan]
0.0
[nan nan nan ... nan nan nan]
0.0

/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:16: RuntimeWarning: overflow encountered in multiply
  app.launch_new_instance()
/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:11: RuntimeWarning: overflow encountered in multiply
  # This is added back by InteractiveShellApp.init_path()
/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:16: RuntimeWarning: invalid value encountered in subtract
  app.launch_new_instance()


0.0
[nan nan nan ... nan nan nan]
0.0
[nan nan nan ... nan nan nan]
0.0
[nan nan nan ... nan nan nan]
0.0
[nan nan nan ... nan nan nan]
0.0
[nan nan nan ... nan nan nan]
0.0
[nan nan nan ... nan nan nan]
0.0
[nan nan nan ... nan nan nan]
0.0
[nan nan nan ... nan nan nan]
0.0
[nan nan nan ... nan nan nan]
0.0
[nan nan nan ... nan nan nan]
0.0
[nan nan nan ... nan nan nan]
0.0
[nan nan nan ... nan nan nan]
0.0
[nan nan nan ... nan nan nan]
0.0
[nan nan nan ... nan nan nan]
0.0
[nan nan nan ... nan nan nan]
0.0
[nan nan nan ... nan nan nan]
0.0
[nan nan nan ... nan nan nan]
0.0
[nan nan nan ... nan nan nan]
0.0
[nan nan nan ... nan nan nan]
0.0
[nan nan nan ... nan nan nan]
0.0
[nan nan nan ... nan nan nan]
0.0
[nan nan nan ... nan nan nan]
0.0
[nan nan nan ... nan nan nan]
0.0
[nan nan nan ... nan nan nan]
0.0
[nan nan nan ... nan nan nan]
0.0
[nan nan nan ... nan nan nan]
0.0
[nan nan nan ... nan nan nan]
0.0
[nan nan nan ... nan nan nan]
0.0
[nan nan nan ... nan nan nan]
0.0
[nan nan n

In [86]:
K_test = kernel(X_scaled,X_test)

print(K_test)
print(alpha)
ans = prediction(K_test,alpha)
print(ans)
print(evaluation(ans, y_test))

[[1.         0.96581414 0.96387412 ... 0.9567961  0.96231821 0.95413711]
 [0.96581414 1.         0.96292023 ... 0.93057582 0.95393836 0.9168926 ]
 [0.96387412 0.96292023 1.         ... 0.95245636 0.95287205 0.96558348]
 ...
 [0.9567961  0.93057582 0.95245636 ... 1.         0.94748536 0.95502192]
 [0.96231821 0.95393836 0.95287205 ... 0.94748536 1.         0.9501881 ]
 [0.95413711 0.9168926  0.96558348 ... 0.95502192 0.9501881  1.        ]]
[-0.00681135 -0.00792363 -0.01172075 ...  0.00895025  0.00416395
  0.01920272]


ValueError: shapes (1953,) and (2000,2000) not aligned: 1953 (dim 0) != 2000 (dim 0)

In [ ]:
K_test